product6:
  outputs:
    dev:
      account: "KUTQCBB-VF37130"
      database: "domain6_db"
      user: "gb"
      password: "Gau@snowland#1"
      role:  "domain6_engginer"
      schema: "product6"
      threads: 1
      type: snowflake
      warehouse:  "domain6_wh"
  target: dev
