
name: Push Contract to Repo

on: [push]


jobs:
  push_contract:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: "product6"
      DOMAIN_NAME: "domain6"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Clone contract repo
      run: git clone https://github.com/bolez/contract.git

    - name: Copy schema
      run: |
        ls -a
        mkdir -p contract/$PROJECT_NAME
        cp $DOMAIN_NAME/models/marts/contracts/* contract/$PROJECT_NAME/*
        

    - name: Commit changes
      # if: env.schema_changed == 'true'
      run: |
        cd contract
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update schema for product_name"
      # if: success()
      
    - name: Push changes
      #if: env.schema_changed == 'true'
      run: |
        cd contract
        git push https://x-access-token:${{ secrets.GH }}@github.com/bolez/contract.git main
      # if: success()
      
